"use strict";

const PDFDocument = require("pdfkit");

const exportPDF = ({ title = "Report", columns = [], data = [] }, res) => {
  const doc = new PDFDocument({
    margin: 40,
    size: "A4",
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=${title}.pdf`);

  doc.pipe(res);

  // Header
  doc.fontSize(20).text("AMIOUT", {
    align: "center",
  });

  doc.moveDown(0.5);

  doc.fontSize(16).text(title, {
    align: "center",
  });

  doc.moveDown();

  doc.fontSize(10).text(`Generated On : ${new Date().toLocaleString()}`);

  doc.moveDown();

  // Table Header
  columns.forEach((column, index) => {
    doc.font("Helvetica-Bold").text(column.header, 40 + index * 120, doc.y, {
      width: 110,
    });
  });

  doc.moveDown();

  // Table Data
  data.forEach((row) => {
    columns.forEach((column, index) => {
      let value = row[column.key];

      if (value === null || value === undefined) {
        value = "";
      }

      if (typeof value === "object") {
        value = JSON.stringify(value);
      }

      doc
        .font("Helvetica")
        .fontSize(10)
        .text(String(value), 40 + index * 120, doc.y, {
          width: 110,
        });
    });

    doc.moveDown();

    if (doc.y > 730) {
      doc.addPage();
    }
  });

  // Footer
  doc.moveDown(2);

  doc.fontSize(10).text("Generated by AMIOUT Smart Outpass Management System", {
    align: "center",
  });

  doc.end();
};

module.exports = Object.freeze({
  exportPDF,
});
